# Summary: GitHub Actions workflow to run flake8 on the codebase.
#
# Copyright 2024 Michael Hucka.
# License: MIT License – see file "LICENSE" in the project website.
# Website: https://github.com/mhucka/urial

name: Lint Python files
run-name: Lint code after ${{github.event_name}} by ${{github.actor}}

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:
    paths:
      - '**.py'

jobs:
  flake8-lint:
    name: Run flake8
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-lint.txt

      - name: Run flake8
        uses: TrueBrain/actions-flake8@v2
        with:
          only_warn: 1
          extra_arguments: "--show-source --config=./.flake8 --extend-exclude=dev/,tests/"
          plugins: flake8>=6.1.0 flake8-bugbear>=23.12.0 flake8-builtins>=2.2.0 flake8-comprehensions>=3.8.0 flake8_implicit_str_concat>=0.4.0 flake8-pie>=0.16.0 flake8-simplify>=0.21.0
